<a href="https://colab.research.google.com/github/216d0136/python_practice/blob/master/lesson30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as  np
x = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
print(x)

x = np.array([1,2,3])
print(x) # [1 2 3]
print(type(x)) # <class 'numpy.ndarray'>

my_list1 = [1,2,3,4,5]
my_array1 = np.array(my_list1) # numpyのarrayを作る

my_list2 = [10,20,30,40,50]
my_lists = [my_list1, my_list2] # リストのリストを作る。
my_lists # [[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]] # リストのリストが完成。

# my_listsを使ってNumPyのアレイを使る。（多次元配列を作る）
my_array2 = np.array(my_lists)

my_array2 # 2行5列の配列ができる。
"""
array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])
"""


[1. 2. 3. 4. 5.]
[1 2 3]
<class 'numpy.ndarray'>


'\narray([[ 1,  2,  3,  4,  5],\n       [10, 20, 30, 40, 50]])\n'